### ISSUE TITLE
Breaking change to ConfigCatClient creation is missing from release notes

### ISSUE THREAD

**Issue by tobinus** [configcat/java-sdk#21]
I tried (or, well, Dependabot tried) to upgrade to the new 8.0.0 release of the SDK, but it fails due to a breaking change to the way you create a new instance of `ConfigCatClient`. In the previous release, you would call [`ConfigCatClient.newBuilder()`](https://javadoc.io/static/com.configcat/configcat-java-client/7.2.0/com/configcat/ConfigCatClient.html#newBuilder--) and set the options through it. Now, you need to call [`ConfigCatClient.get(sdkKey[, optionsCallback])`](https://javadoc.io/static/com.configcat/configcat-java-client/8.0.0/com/configcat/ConfigCatClient.html#get-java.lang.String-java.util.function.Consumer-). I suggest you mention this in [the release notes](https://github.com/configcat/java-sdk/releases/tag/v8.0.0), since everyone needs to adapt to this change 🙂 (The existing note about `ConfigCatClient.get` does not make any sense, since that method did not even exist in the previous release, by the way.)

**Comment by novalisdenahi** [comment]
Hi @tobinus,

You are right, the release notes was not fully complete. Thanks for noticing and letting us know.
I just updated the release notes with the new singleton creation and the default user settings which were missing.

You can find more info about the new features in the [Java SDK documentation](https://configcat.com/docs/sdk-reference/java/).

Let us know, if you have any questions regarding the changes. 

Best Regards,
Daniel

**Comment by tobinus** [comment]
> You are right, the release notes was not fully complete. Thanks for noticing and letting us know.

You're welcome!

>  I just updated the release notes with the new singleton creation and the default user settings which were missing.

Thank you! The release notes are better now. Though they do mention:

> Client initialization options were moved to a Options object that can be passed to the new ConfigCatClient.get() factory method.

This is slightly incorrect, since you may pass a _Consumer_ that is given an Options object, which it can then configure.

Speaking of, this part is not really explained in the Java SDK documentation. It only mentions that you can create/get a client with the default options, immediately followed by a table of Options method with no context for what they are for, followed by a single example. I wish the documentation showed the signature of `ConfigCatClient.get(sdkKey, optionsCallback)` and explained how you set those options in text.

**Comment by novalisdenahi** [comment]
Hi @tobinus,

We updated the release notes last week. Now, it mentions the `Consumer` properly. 

We also updated the Java SDK docs as well, you can find a more detailed description how to create/get the client with options [Customizing the ConfigCat Client](https://configcat.com/docs/sdk-reference/java/#customizing-the-configcat-client).

Let us know, if you have any questions regarding the changes.

Best Regards,
Daniel
