### ISSUE TITLE
BeanCreationException error after upgrading to version 8.x

### ISSUE THREAD

**Issue by rafa-acioly** [configcat/java-sdk#35]
### Describe the bug

After upgrading java from version `16` to `17` and upgrading the `config-cat` lib from vesion `6.x` to `8.x`, the Bean creation on spring started to fail with the exception `BeanCreationException`

### To reproduce

Upgrade java vertion to `17` and `config-cat` to `8.x`

```
<dependency>
      <groupId>com.configcat</groupId>
      <artifactId>configcat-java-client</artifactId>
      <version>[8.0.0,)</version>
    </dependency>
```

Change the bean creation from:

```groovy
@Bean
    ConfigCatClient configCatClient() {
        return ConfigCatClient
            .newBuilder()
            .mode(PollingModes.autoPoll(60))
            .logLevel(LogLevel.WARNING)
            .build(this.settings.sdkKey)
    }
```

To:

```groovy
import com.configcat.*;

@Bean
    ConfigCatClient configCatClient() {
        return ConfigCatClient.get(this.settings.sdkKey, options -> {
          options.pollingMode(PollingModes.autoPoll());
          options.logLevel(LogLevel.WARNING);
        })
    }
```

The error:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configCatClient' defined in class path resource [br/com/blz/myrepo/config/ConfigCat.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.configcat.ConfigCatClient]: Factory method 'configCatClient' threw exception; nested exception is java.lang.reflect.GenericSignatureFormatError: Signature Parse error: expected a class type
```

**Comment by novalisdenahi** [comment]
Hi, @rafa-acioly!
Thank you for the issue! I will check on the problem and let you know if we fixed the problem.

**Comment by rafa-acioly** [comment]
@novalisdenahi Is there a temporary solution to this? Maybe another version?

**Comment by novalisdenahi** [comment]
@rafa-acioly Can you provide me with a little bit more info? I tried to reproduce the error, but I couldn't do it.
Worked with Maven and Gradle as well. Different java versions, and I tried other versions of org.springframework.boot plugin as well (maven/gradle both worked well).

Can you try with the fix 8.1.0 configcat-java-client version?
Also, can you provide me with the exact java and spring version?

Thanks in advance!

**Comment by rafa-acioly** [comment]
@novalisdenahi I found the error cause, for some reason the `newrelic` library was having problem with `completabe future` and was messing up everything.

**Comment by novalisdenahi** [comment]
@rafa-acioly Did you manage to solve the problem?  Let us know if everything works fine so we can close the issue.
Otherwise, please provide us with more info regarding the cause of the problem.

Thanks in advance!
